server:
  port: 9527

spring:
  application:
    name: cloud-gateway-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，然后利用微服务名进行路由
      routes:
        - id: payment-service-1 #路由的ID，自定义，但要求唯一
          # uri: http://localhost:8001 #路由匹配到的访问地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/hystrix/ok/** #断言；路径匹配才路由
        - id: payment-service-2 #路由的ID，自定义，但要求唯一
          # uri: http://localhost:8002 #路由匹配到的访问地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/get/** #断言；路径匹配才路由

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka # 单机版
  instance:
    instance-id: gateway9527

