server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false # 是否注册到注册中心，这里是服务端，不需要注册
    fetch-registry: false # false表示自己就是注册中心，职责就是维护服务实例，不需要去检索服务
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/ # eureka服务端地址
